spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口

logging:
  level:
    root: info
    com.macro.mall: debug
aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5t98PEYbt9w8qhxJWXkb # 访问身份验证中用到用户标识
    accessKeySecret: wQklHKW6iQBMMA0tRsnjAczhO0Y29a # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: tulingmall-demo # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    #callback:  # 文件上传成功后的回调地址
    dir:
      prefix: user-dir-prefix/ # 上传文件夹路径前缀
